### ISSUE TITLE
ValueError: Variable d_bn1/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/ does not exist

### ISSUE THREAD

**Issue by pageedward** [bamos/dcgan-completion.tensorflow#28]
when i train model ,errors happened ,...please help me

Traceback (most recent call last):
  File "./train-dcgan.py", line 39, in <module>
    is_crop=False, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/home/page/wp/dcgan-completion.tensorflow/model.py", line 65, in __init__
    self.build_model()
  File "/home/page/wp/dcgan-completion.tensorflow/model.py", line 81, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.G, reuse=False)
  File "/home/page/wp/dcgan-completion.tensorflow/model.py", line 312, in discriminator
    h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d_h1_conv')))
  File "/home/page/wp/dcgan-completion.tensorflow/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/moving_averages.py", line 375, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 123, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 103, in create_slot
    return _create_slot_var(primary, val, '')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_bn1/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by nests01** [comment]
me too.
Have you solved it?

**Comment by powder21** [comment]
I guess the version of your tf is >=1.0 when you reuse the D network,`train=True`is needed,just like`h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d%d_h1_conv' % self.data_number), train=not reuse))`

**Comment by powder21** [comment]
I guess the version of your tf is >=1.0.when you reuse the D network,`train=True`is needed,just like`h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d_h1_conv'), train=not reuse))`

**Comment by powder21** [comment]
you can fork [original version of this DCGAN code](https://github.com/carpedm20/DCGAN-tensorflow/blob/master/model.py)

**Comment by royyannick** [comment]
Same problem when trying to run the complete.py

**Comment by bamos** [comment]
I've updated the code to a more recent version of TF (>=1.0) and this issue shouldn't happen anymore if you're also running TF >= 1.0.

**Comment by sachinjm** [comment]
even though TF>=1.0.0 I am getting NotFoundError (see above for traceback): Key discriminator/d_bn0/beta not found in checkpoint

Got above error while running ./complete.py ./data/your-test-data/aligned/* --outDir outputImages

I am trying to complete one image of size 64x64. (its not aligned)

Please help me out
