### ISSUE TITLE
Error while running ./train-dcgan.py --dataset ./data/your-dataset/aligned --epoch 20

### ISSUE THREAD

**Issue by samuelhsilva** [bamos/dcgan-completion.tensorflow#30]
I am trying to run this part of the code, but I getting the following error:
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "./train-dcgan.py", line 39, in <module>
    is_crop=False, checkpoint_dir=FLAGS.checkpoint_dir)
  File "/home/samuel/Desktop/DL_Final_Project/dcgan-completion.tensorflow/model.py", line 65, in __init__
    self.build_model()
  File "/home/samuel/Desktop/DL_Final_Project/dcgan-completion.tensorflow/model.py", line 75, in build_model
    self.z_sum = tf.histogram_summary("z", self.z)
AttributeError: 'module' object has no attribute 'histogram_summary'

Did anyone had the same problem? If so, how do I solve it?

**Comment by bamos** [comment]
The code should be updated to the latest version of TF. There is a PR for this but I'm not sure if it works.
