### ISSUE TITLE
Cannot feed value of shape (64, 64, 64) for Tensor 'real_images:0', which has shape '(?, 64, 64, 3)'

### ISSUE THREAD

**Issue by roshan-raj** [bamos/dcgan-completion.tensorflow#78]
[*] Reading checkpoints...

======
An existing model was found in the checkpoint directory.
If you just cloned this repository, it's a model for faces
trained on the CelebA dataset for 20 epochs.
If you want to train a new model from scratch,
delete the checkpoint directory or specify a different
--checkpoint_dir argument.
======

Traceback (most recent call last):
  File "train-dcgan.py", line 41, in <module>
    dcgan.train(FLAGS)
  File "E:\Engineering\7th SEM\Final Project 2\Referal Codes\dcgan-completion.tensorflow\model.py", line 212, in train
    feed_dict={ self.images: batch_images, self.z: batch_z, self.is_training: True })
  File "C:\Users\Dell\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Dell\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 64, 64) for Tensor 'real_images:0', which has shape '(?, 64, 64, 3)'

**Comment by leilyb** [comment]
Hi ,
Your images should be 64*64 size and RGB. If the images are not RGB, you should change the value of 'c_dim' to 1(originaly this value is 3).
