### ISSUE TITLE
Issues while training the model

### ISSUE THREAD

**Issue by gvpriya** [bamos/dcgan-completion.tensorflow#82]
Hello, I am trying to train the model as specified in the blog. When I executed 
./train-dcgan.py --dataset ./data/you-dataset/aligned --epoch 20, I see below errors 
Traceback (most recent call last):
  File "./train-dcgan.py", line 32, in <module>
    dcgan = DCGAN(sess, image_size=FLAGS.image_size, batch_size=FLAGS.batch_size,is_crop=False,checkpoint_dir=FLAGS.checkpoint_dir)
  File "./dcgan-completion.tensorflow/model.py", line 75, in __init__
    self.build_model()
  File "./dcgan-completion.tensorflow/model.py", line 86, in build_model
    self.z_sum = tf.summary.histogram("z", self.z)
AttributeError: 'module' object has no attribute 'histogram'
Please help me to fix these issues. I am training on LFW Dataset.

**Comment by gvpriya** [comment]
Resolved this. The TensorFlow version was older version. Updated version of TensorFlow to 0.12. But now I am facing sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'. Any leads in fixing this will be helpful.
